# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s8PK5p3zyRB3A0bylMBg21-c4L9IX9WI
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv('final.csv')

xVars = df.drop('suicides_per_100k', axis= 1)
yVars = df[['suicides_per_100k']]
xTrain, xValid, yTrain, yValid = train_test_split(xVars, yVars, test_size = 0.3, random_state= 42)

regressor = RandomForestRegressor(n_estimators= 3000, random_state = 50)
regressor.fit(xTrain, yTrain)

y_pred = regressor.predict(xValid)

metrics.mean_squared_error(yValid, y_pred)

metrics.mean_absolute_error(yValid, y_pred)

metrics.r2_score(yValid, y_pred)

metrics.mean_squared_error(yValid, y_pred,squared=False)

feature_names = xVars.columns
feature_importance = pd.DataFrame(regressor.feature_importances_, index = feature_names).sort_values(0, ascending=False)
feature_importance